// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnError } from "./TurnError";

export type ErrorNotification = { error: TurnError, willRetry: boolean,
/**
 * Delay before the automatic retry begins, in milliseconds.
 */
retryAfterMs: number | null, threadId: string, turnId: string, };
