// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRequestProgressPhase } from "./ModelRequestProgressPhase";

export type ModelRequestProgressNotification = { threadId: string, turnId: string, phase: ModelRequestProgressPhase, sentBytes: bigint, receivedBytes: bigint, };
