// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { ThreadFileChangeDisposition } from "./ThreadFileChangeDisposition";
import type { ThreadFileChangeKind } from "./ThreadFileChangeKind";

export type ThreadFileChange = { environmentId: string, path: LegacyAppPathString, changeKind: ThreadFileChangeKind, disposition: ThreadFileChangeDisposition, detail: string | null, };
