// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit strategy for a manual or provider-configured context compaction.
 */
export type CompactionMode = "local" | "remotev1" | "remotev2";
